# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideDish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SideDish

  target 'SideDishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Toast-Swift', '~> 5.0.0'
  pod 'Alamofire', '4.7.3'

end
