# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SideDishApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Toast-Swift', '~> 5.0.0'

  # Pods for SideDishApp

  target 'SideDishAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftLint'
    pod 'Toast-Swift', '~> 5.0.0'
  end

  target 'SideDishAppUITests' do
    # Pods for testing
    pod 'SwiftLint'
    pod 'Toast-Swift', '~> 5.0.0'
  end

end
