# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideDishProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SideDishProject
  
  pod 'SwiftLint'
  pod 'Toaster' 
 
  target 'SideDishProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SideDishProjectUITests' do
    # Pods for testing
  end
end
