# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideDish20' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SideDish20

  target 'SideDish20Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SideDish20UITests' do
    # Pods for testing
  end
pod 'SwiftLint'
pod 'Toaster'
end
