SET foreign_key_checks = 0;

DROP TABLE IF EXISTS category;
CREATE TABLE category
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME          VARCHAR(64),
    PRODUCT_COUNT INT
);

DROP TABLE IF EXISTS product;
CREATE TABLE product
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME                VARCHAR(64),
    PRICE               INT,
    DESCRIPTION         VARCHAR(512),
    THUMBNAIL_IMAGE_URL VARCHAR(512),
    STOCK               INT,
    CATEGORY_ID         BIGINT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES category (ID)
);

DROP TABLE IF EXISTS delivery;
CREATE TABLE delivery
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    REGION     VARCHAR(64),
    TYPE       VARCHAR(64)
);

DROP TABLE IF EXISTS event;
CREATE TABLE event
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME          VARCHAR(64),
    DISCOUNT_RATE DOUBLE
);

DROP TABLE IF EXISTS product_delivery;
CREATE TABLE product_delivery
(
    PRODUCT_ID  BIGINT,
    DELIVERY_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES product (ID),
    FOREIGN KEY (DELIVERY_ID) REFERENCES delivery (ID)
);

DROP TABLE IF EXISTS product_event;
CREATE TABLE product_event
(
    PRODUCT_ID BIGINT,
    EVENT_ID   BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES product (ID),
    FOREIGN KEY (EVENT_ID) REFERENCES event (ID)
);

DROP TABLE IF EXISTS image;
CREATE TABLE image
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    URL        VARCHAR(512),
    PRODUCT_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES product (ID)
);

SET foreign_key_checks = 1;
