DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME          VARCHAR(64),
    PRODUCT_COUNT INT
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(64),
    PRICE       INT,
    DISCRIPTION VARCHAR(512),
    STOCK       INT,
    CATEGORY_ID BIGINT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);

DROP TABLE IF EXISTS DELIVERY;
CREATE TABLE DELIVERY
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    REGION     VARCHAR(64),
    TYPE       VARCHAR(64),
    FREE_PRICE INT,
    FEE        INT
);

DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME          VARCHAR(64),
    DISCOUNT_RATE DOUBLE
);

DROP TABLE IF EXISTS PRODUCT_DELIVERY;
CREATE TABLE PRODUCT_DELIVERY
(
    PRODUCT_ID  BIGINT,
    DELIVERY_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY (ID)
);

DROP TABLE IF EXISTS PRODUCT_EVENT;
CREATE TABLE PRODUCT_EVENT
(
    PRODUCT_ID BIGINT,
    EVENT_ID   BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID)
);

DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IMAGE
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    URL        VARCHAR(512),
    PRODUCT_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
