-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 12:24:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sidedish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sidedish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sidedish` DEFAULT CHARACTER SET utf8 ;
USE `sidedish` ;

-- -----------------------------------------------------
-- Table `sidedish`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidedish`.`menu` ;

CREATE TABLE IF NOT EXISTS `sidedish`.`menu` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(255) NOT NULL,
                                                 `description` VARCHAR(255) NOT NULL,
                                                 `price` INT NOT NULL,
                                                 `menu_type` INT NOT NULL,
                                                 `sale_type` INT NOT NULL,
                                                 `fee` INT NOT NULL,
                                                 `free_shipping_min` INT NOT NULL,
                                                 `delivery_info` INT NOT NULL,
                                                 `stock` INT NOT NULL,
                                                 `image_id` INT NOT NULL,
                                                 PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidedish`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidedish`.`image` ;

CREATE TABLE IF NOT EXISTS `sidedish`.`image` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `menu_id` INT NOT NULL,
                                                  `image_path` VARCHAR(1000) NOT NULL,
                                                  `is_main_image` TINYINT NOT NULL,
                                                  PRIMARY KEY (`id`),
                                                  INDEX `fk_image_menu_idx` (`menu_id` ASC) VISIBLE,
                                                  CONSTRAINT `fk_image_menu`
                                                      FOREIGN KEY (`menu_id`)
                                                          REFERENCES `sidedish`.`menu` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidedish`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidedish`.`user` ;

CREATE TABLE IF NOT EXISTS `sidedish`.`user` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `address` VARCHAR(255) NOT NULL,
                                                 `name` VARCHAR(45) NOT NULL,
                                                 PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidedish`.`menu_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidedish`.`menu_order` ;

CREATE TABLE IF NOT EXISTS `sidedish`.`menu_order` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `menu_id` INT NOT NULL,
                                                       `user_id` INT NOT NULL,
                                                       `quantity` INT UNSIGNED NOT NULL,
                                                       PRIMARY KEY (`id`, `menu_id`),
                                                       INDEX `fk_menu_order_user1_idx` (`user_id` ASC) VISIBLE,
                                                       INDEX `fk_menu_order_menu1_idx` (`menu_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_menu_order_user1`
                                                           FOREIGN KEY (`user_id`)
                                                               REFERENCES `sidedish`.`user` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_menu_order_menu1`
                                                           FOREIGN KEY (`menu_id`)
                                                               REFERENCES `sidedish`.`menu` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
