# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'BanchanApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BanchanApp
  pod 'Toaster'
  pod 'SwiftLint'

end
