spring:
  profiles:
    default: ${profile}

oauth2:
  provider:
    github: https://github.com/login/oauth/access_token
    user-info-uri: https://api.github.com/user

jwt:
  access-token:
    expire-length: 10000
  token:
    secret-key: ${JWT_SECRET}
