spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_USER_NAME}
    password: ${AWS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level.com.sidedish: debug
