spring:
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
logging:
  level.com.sidedish: debug
