-- main
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('오리 주물럭_반조리','감칠맛 나는 매콤한 양념','15800','100','main','bbb','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('잡채','탱글한 면발과 맛깔진 고명이 가득','11610','100','main','bbb','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/310_ZIP_P_0012_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('소갈비찜','촉촉하게 밴 양념이 일품','28900','100','main','bbb','런칭특가,이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('간장 코다리조림','쫀득한 코다리를 국내산 간장소스로 맛있게 조렸어요','14900','100','main','bbb','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('꼬막비빔밥','매콤하게 입맛 돋우는','7800','100','main','bbb','런칭특가,이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('궁중 떡볶이_반조리','영양 듬뿍 프리미엄 간장 떡볶이','11800','100','main','bbb','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('초계국수_쿠킹박스','건강한 가정 간편식 여름 국수','12800','100','main','bbb','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('쭈꾸미 한돈 제육볶음_반조림','쫄깃한 쭈꾸미와 고소한 돼지고기가 일품','16900','100','main','bbb','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');

---- soup
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('한돈 돼지 김치찌개','김치찌개에는 역시 돼지고기','9300','100','soup','반찬','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('된장찌개','특별하지 않아서 더 좋은 우리맛','7800','100','soup','반찬','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('미역오이냉국','여름엔 시원한 냉국이 최고','6000','100','soup','반찬','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('동태찌개','겨울철 보양식으로 안성맞춤','7800','100','soup','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('감자국','국내산 감자라 더 고소한','6000','100','soup','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('우리콩 강된장찌개','우리콩으로 만들어 안심','7800','100','soup','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('순한 오징어무국','부드럽고 담백한 국물','6000','100','soup','반찬','런칭특가,이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('맑은 동태구','시원함과 감칠맛은 그대로 담은 맑은 국','8000','100','soup','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');

---- side
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('새콤달콤 오징어무침','국내산 오징어를 새콤달콤하게','7500','100','side','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('호두 멸치볶음','잔멸치와 호두가 만나 짭쪼름하지만 고소하게!','6800','100','side','반찬','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('한돈 매콤 안심장조림','부드러운 한돈 안심살의 매콤함','8000','100','side','반찬','런칭특가,이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('야채 어묵볶음','첨가물 없는 순수어묵과 야채의 만남','7200','100','side','반찬','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('오이소박이','깔끔하고 개운한 여름 김치','6800','100','side','반찬','이벤트특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('두부조림','각종 영양이 가득 담긴','7200','100','side','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('미나리무침','향긋하고 고소한 봄나물','6800','100','side','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
INSERT INTO PRODUCT (name, content, price, quantity, dish_type, side_dish_type, apply_event, img_url) VALUES ('참외오이무침','시원하고 아삭한 여름 생채 무침','6300','100','side','반찬','런칭특가','http://public.codesquad.kr/jk/storeapp/data/main/1155_ZIP_P_0081_T.jpg');
