export const CATEGORY_TEXTS = [
  {
    main: '든든한 메인요리',
    sub: ['육류 요리', '해산물 요리'],
  },
  { main: '뜨끈한 국물요리', sub: ['국/탕/찌개'] },
  { main: '정갈한 밑반찬', sub: ['나물/무침', '조림/볶음', '절임/장아찌'] },
];

export const MAIN_ITEMS = {
  id: 1,
  title: '식탁을 풍성하게 하는 정갈한 밑반찬',
  data: [
    {
      id: 1,
      img: 'https://random.imagecdn.app/412/412',
      name: '1',
      description: '감칠맛 나는 매콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송, 전국 택배',
    },
    {
      id: 2,
      img: 'https://random.imagecdn.app/412/412',
      name: '2',
      description: '감칠맛 나는 매콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '이벤트특가',
      deliveryType: '전국 택배',
    },
    {
      id: 3,
      img: 'https://random.imagecdn.app/412/412',
      name: '3',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송, 전국 택배',
    },
    {
      id: 4,
      img: 'https://random.imagecdn.app/412/412',
      name: '4',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
    {
      id: 5,
      img: 'https://random.imagecdn.app/412/412',
      name: '5',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
    {
      id: 6,
      img: 'https://random.imagecdn.app/412/412',
      name: '6',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
    {
      id: 7,
      img: 'https://random.imagecdn.app/412/412',
      name: '7',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
    {
      id: 8,
      img: 'https://random.imagecdn.app/412/412',
      name: '8',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
    {
      id: 9,
      img: 'https://random.imagecdn.app/412/412',
      name: '9',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
    {
      id: 10,
      img: 'https://random.imagecdn.app/412/412',
      name: '10',
      description: '감칠맛 나는 달콤한 양념',
      discountPrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
  ],
};

export const TAB_BAR_ITEMS = [
  {
    id: 1,
    name: '풍성한 고기 반찬',
  },
  {
    id: 2,
    name: '편리한 반찬 세트',
  },
  {
    id: 3,
    name: '맛있는 제철 요리',
  },
  { id: 4, name: '우리 아이 영양 반찬' },
];

export const RECOMMEND_ITEMS = [
  {
    id: 1,
    name: '풍성한 고기 반찬',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        name: '오리 주물럭_반조리',
        description: '감칠맛 나는 매콤한 양념',
        discountPrice: 12640,
        price: 15800,
        tag: '런칭특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        name: '돼지 주물럭_반조리',
        description: '감칠맛 나는 매콤한 양념',
        discountPrice: 12640,
        price: 15800,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        name: '달콤 오리 주물럭_반조리',
        description: '감칠맛 나는 달콤한 양념',
        discountPrice: 12640,
        price: 15800,
        tag: '런칭특가',
        deliveryType: '전국 택배',
      },
    ],
  },
  {
    id: 2,
    name: '편리한 반찬 세트',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        name: '간장 소갈비찜',
        description: '촉촉하게 벤 양념이 일품',
        discountPrice: 26010,
        price: 28900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        name: '매운 소갈비찜',
        description: '촉촉하게 벤 양념이 일품',
        discountPrice: 26010,
        price: 28900,
        tag: '런칭특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        name: '마라 소갈비찜',
        description: '촉촉하게 벤 양념이 일품',
        discountPrice: 26010,
        price: 28900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
    ],
  },
  {
    id: 3,
    name: '맛있는 제철 요리',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        name: '간장 쭈꾸미',
        description: '쫄낏한 쭈구미',
        // discountPrice: 16900,
        price: 16900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        name: '매콤 쭈꾸미',
        description: '쫄낏한 쭈구미',
        // discountPrice: 16900,
        price: 16900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        name: '쭈꾸미',
        description: '쫄낏한 쭈구미',
        // discountPrice: 16900,
        price: 16900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
    ],
  },
  {
    id: 4,
    name: '우리 아이 영양 반찬',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        name: '새콤달콤 오징어무침',
        description: '국내산 오징어를 새콤달콤하게',
        discountPrice: 6000,
        price: 7500,
        tag: '런칭특가',
        deliveryType: '새벽 배송',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        name: '새콤달콤 오징어무침',
        description: '국내산 오징어를 새콤달콤하게',
        discountPrice: 6000,
        price: 7500,
        tag: '런칭특가',
        deliveryType: '전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        name: '새콤달콤 오징어무침',
        description: '국내산 오징어를 새콤달콤하게',
        discountPrice: 6000,
        price: 7500,
        tag: '런칭특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
    ],
  },
];
