export const CATEGORY_TEXTS = [
  {
    main: '든든한 메인요리',
    sub: ['육류 요리', '해산물 요리'],
  },
  { main: '뜨끈한 국물요리', sub: ['국/탕/찌개'] },
  { main: '정갈한 밑반찬', sub: ['나물/무침', '조림/볶음', '절임/장아찌'] },
];

export const MAIN_ITEMS = {
  id: 1,
  title: '식탁을 풍성하게 하는 정갈한 밑반찬',
  data: [
    {
      id: 1,
      img: 'https://random.imagecdn.app/412/412',
      title: '오리 주물럭_반조리',
      desc: '감칠맛 나는 매콤한 양념',
      salePrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송, 전국 택배',
    },
    {
      id: 2,
      img: 'https://random.imagecdn.app/412/412',
      title: '돼지 주물럭_반조리',
      desc: '감칠맛 나는 매콤한 양념',
      salePrice: 12640,
      normalPrice: 15800,
      tag: '이벤트특가',
      deliveryType: '전국 택배',
    },
    {
      id: 3,
      img: 'https://random.imagecdn.app/412/412',
      title: '달콤 오리 주물럭_반조리',
      desc: '감칠맛 나는 달콤한 양념',
      salePrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송, 전국 택배',
    },
    {
      id: 4,
      img: 'https://random.imagecdn.app/412/412',
      title: '달콤 오리 주물럭_반조리',
      desc: '감칠맛 나는 달콤한 양념',
      salePrice: 12640,
      normalPrice: 15800,
      tag: '런칭특가',
      deliveryType: '새벽 배송',
    },
  ],
};

export const RECOMMEND_ITEMS = [
  {
    id: 1,
    title: '풍성한 고기 반찬',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        title: '오리 주물럭_반조리',
        desc: '감칠맛 나는 매콤한 양념',
        salePrice: 12640,
        normalPrice: 15800,
        tag: '런칭특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        title: '돼지 주물럭_반조리',
        desc: '감칠맛 나는 매콤한 양념',
        salePrice: 12640,
        normalPrice: 15800,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        title: '달콤 오리 주물럭_반조리',
        desc: '감칠맛 나는 달콤한 양념',
        salePrice: 12640,
        normalPrice: 15800,
        tag: '런칭특가',
        deliveryType: '전국 택배',
      },
    ],
  },
  {
    id: 2,
    title: '편리한 반찬 세트',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        title: '간장 소갈비찜',
        desc: '촉촉하게 벤 양념이 일품',
        salePrice: 26010,
        normalPrice: 28900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        title: '매운 소갈비찜',
        desc: '촉촉하게 벤 양념이 일품',
        salePrice: 26010,
        normalPrice: 28900,
        tag: '런칭특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        title: '마라 소갈비찜',
        desc: '촉촉하게 벤 양념이 일품',
        salePrice: 26010,
        normalPrice: 28900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
    ],
  },
  {
    id: 3,
    title: '맛있는 제철 요리',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        title: '간장 쭈꾸미',
        desc: '쫄낏한 쭈구미',
        // salePrice: 16900,
        normalPrice: 16900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        title: '매콤 쭈꾸미',
        desc: '쫄낏한 쭈구미',
        // salePrice: 16900,
        normalPrice: 16900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        title: '쭈꾸미',
        desc: '쫄낏한 쭈구미',
        // salePrice: 16900,
        normalPrice: 16900,
        tag: '이벤트특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
    ],
  },
  {
    id: 4,
    title: '우리 아이 영양 반찬',
    data: [
      {
        id: 1,
        img: 'https://random.imagecdn.app/412/412',
        title: '새콤달콤 오징어무침',
        desc: '국내산 오징어를 새콤달콤하게',
        salePrice: 6000,
        normalPrice: 7500,
        tag: '런칭특가',
        deliveryType: '새벽 배송',
      },
      {
        id: 2,
        img: 'https://random.imagecdn.app/412/412',
        title: '새콤달콤 오징어무침',
        desc: '국내산 오징어를 새콤달콤하게',
        salePrice: 6000,
        normalPrice: 7500,
        tag: '런칭특가',
        deliveryType: '전국 택배',
      },
      {
        id: 3,
        img: 'https://random.imagecdn.app/412/412',
        title: '새콤달콤 오징어무침',
        desc: '국내산 오징어를 새콤달콤하게',
        salePrice: 6000,
        normalPrice: 7500,
        tag: '런칭특가',
        deliveryType: '새벽 배송, 전국 택배',
      },
    ],
  },
];
